[package]
name = "common"
version = "0.1.0"
edition = "2021"
description = "Common utility to share between UI and BE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
